[package]
name = "mos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
color-eyre = "0.6"
dirs = "7"
chrono = "0.4"
hostname = "0.4"
walkdir = "2"
toml = "1.1.2"
dialoguer = "0.12"
toml_edit = "0.25.11"
which = "8.0.2"
colored = "3.1.1"
